//App

//Input

//Data

const model = {
    app: {
        currentPage: "otherProfiles", // login, register, tripOverview, tripView, myProfile
                                //friendsOverview, otherProfiles, friendsProfile, chatOverview, feedView, footerView
        loggedInUser: null,
        tripId: 2,
        shownUserID: 5,
        buttons:[{ // Currently not in use
                functionName: 'myPage',
                buttonName: 'Min Side',
            },
            {
                functionName: 'hikeSugestion',
                buttonName: 'TurForslag',
            },
        ],
        
    }, 

    input: {
        loginForm: {
            email: null,
            password: null,
        },
        createAccount:{
            userName: null,
            email: null,
            password: null,
            repeatPassword: null,
        }, 
        searchField:{
            searchText: null,
        },
        myProfile:{
            userPicture: null,
            userPhysical: 0,
        },
        
    },

    data: {
        userProfile: [ 
            {
                id: 0,
                userFullName: "Jørgine Heffalompen",
                userName: "Jørgine",
                email: "eksempel@gmail.com",
                password: "hei123",
                userPicture: "img/placeholder.jpg",
                userPhysical: 0,
                location: "Oslo",
                friendsListId: [2, 3, 4, 7, 8, 9, 10],
                pendingRequests: [5, 6],
                kilometresWalked: 0,
                tripsTaken: 0,
                achievementView: ["10km", "20km"],
            },
            {
                id: 1,
                userFullName: "Emma Larsson",
                userName: "EmmaL",
                email: "emma.l@gmail.com",
                password: "trail345",
                userPicture: "img/placeholder.jpg",
                userPhysical: 3,
                location: "Bergen",
                friendsListId: [3, 4, 7],
                pendingRequests: [2],
                kilometresWalked: 78,
                tripsTaken: 12,
                achievementView: ["10km", "20km", "50km", "10trips"],
            },
            {
                id: 2,
                userFullName: "Erik Hansen",
                userName: "ErikH",
                email: "erik.hansen@gmail.com",
                password: "secure456",
                userPicture: "img/placeholder.jpg",
                userPhysical: 4,
                location: "Oslo",
                friendsListId: [0, 3, 4],
                pendingRequests: [7],
                kilometresWalked: 156,
                tripsTaken: 25,
                achievementView: ["10km", "20km", "50km", "100km", "10trips", "25trips"],
            },
            {
                id: 3,
                userFullName: "Maria Larsen",
                userName: "MariaL",
                email: "maria.l@gmail.com",
                password: "hiking789",
                userPicture: "img/placeholder.jpg",
                userPhysical: 5,
                location: "Bergen",
                friendsListId: [0, 1, 2, 4, 5],
                pendingRequests: [],
                kilometresWalked: 283,
                tripsTaken: 42,
                achievementView: ["10km", "20km", "50km", "100km", "200km", "10trips", "25trips", "40trips"],
            },
            {
                id: 4,
                userFullName: "Anders Pedersen",
                userName: "AndersP",
                email: "anders.p@gmail.com",
                password: "nature123",
                userPicture: "img/placeholder.jpg",
                userPhysical: 3,
                location: "Trondheim",
                friendsListId: [0, 1, 2, 3],
                pendingRequests: [6],
                kilometresWalked: 89,
                tripsTaken: 15,
                achievementView: ["10km", "20km", "50km", "10trips"],
            },
            {
                id: 5,
                userFullName: "Sofia Berg",
                userName: "SofiaB",
                email: "sofia.b@gmail.com",
                password: "walk456",
                userPicture: "img/placeholder.jpg",
                userPhysical: 2,
                location: "Stavanger",
                friendsListId: [3, 8],
                pendingRequests: [],
                kilometresWalked: 45,
                tripsTaken: 8,
                achievementView: ["10km", "20km"],
            },
            {
                id: 6,
                userFullName: "Lars Nilsen",
                userName: "LarsN",
                email: "lars.n@gmail.com",
                password: "trek789",
                userPicture: "img/placeholder.jpg",
                userPhysical: 1,
                location: "Tromsø",
                friendsListId: [],
                pendingRequests: [0, 4],
                kilometresWalked: 12,
                tripsTaken: 2,
                achievementView: ["10km"],
            },
            {
                id: 7,
                userFullName: "Kristin Olsen",
                userName: "KristinO",
                email: "kristin.o@gmail.com",
                password: "hike101",
                userPicture: "img/placeholder.jpg",
                userPhysical: 4,
                location: "Bodø",
                friendsListId: [0, 1],
                pendingRequests: [],
                kilometresWalked: 167,
                tripsTaken: 28,
                achievementView: ["10km", "20km", "50km", "100km", "10trips", "25trips"],
            },
            {
                id: 8,
                userFullName: "Henrik Dahl",
                userName: "HenrikD",
                email: "henrik.d@gmail.com",
                password: "mountain567",
                userPicture: "img/placeholder.jpg",
                userPhysical: 5,
                location: "Kristiansand",
                friendsListId: [0, 5, 9, 10],
                pendingRequests: [],
                kilometresWalked: 312,
                tripsTaken: 45,
                achievementView: ["10km", "20km", "50km", "100km", "200km", "300km", "10trips", "25trips", "40trips"],
            },
            {
                id: 9,
                userFullName: "Ingrid Bakken",
                userName: "IngridB",
                email: "ingrid.b@gmail.com",
                password: "trail202",
                userPicture: "img/placeholder.jpg",
                userPhysical: 3,
                location: "Ålesund",
                friendsListId: [0, 8, 10, 11],
                pendingRequests: [],
                kilometresWalked: 134,
                tripsTaken: 22,
                achievementView: ["10km", "20km", "50km", "100km", "10trips", "20trips"],
            },
            {
                id: 10,
                userFullName: "Thomas Moen",
                userName: "ThomasM",
                email: "thomas.m@gmail.com",
                password: "path303",
                userPicture: "img/placeholder.jpg",
                userPhysical: 4,
                location: "Drammen",
                friendsListId: [0, 8, 9, 12],
                pendingRequests: [],
                kilometresWalked: 198,
                tripsTaken: 31,
                achievementView: ["10km", "20km", "50km", "100km", "10trips", "25trips", "30trips"],
            },
            {
                id: 11,
                userFullName: "Nina Strand",
                userName: "NinaS",
                email: "nina.s@gmail.com",
                password: "walk404",
                userPicture: "img/placeholder.jpg",
                userPhysical: 2,
                location: "Moss",
                friendsListId: [9],
                pendingRequests: [8],
                kilometresWalked: 67,
                tripsTaken: 11,
                achievementView: ["10km", "20km", "50km", "10trips"],
            },
            {
                id: 12,
                userFullName: "Ole Jensen",
                userName: "OleJ",
                email: "ole.j@gmail.com",
                password: "trek505",
                userPicture: "img/placeholder.jpg",
                userPhysical: 5,
                location: "Sandefjord",
                friendsListId: [10, 13, 14],
                pendingRequests: [15],
                kilometresWalked: 245,
                tripsTaken: 38,
                achievementView: ["10km", "20km", "50km", "100km", "200km", "10trips", "25trips"],
            },
            {
                id: 13,
                userFullName: "Anna Haugen",
                userName: "AnnaH",
                email: "anna.h@gmail.com",
                password: "nature606",
                userPicture: "img/placeholder.jpg",
                userPhysical: 3,
                location: "Tønsberg",
                friendsListId: [12, 14],
                pendingRequests: [],
                kilometresWalked: 112,
                tripsTaken: 19,
                achievementView: ["10km", "20km", "50km", "100km", "10trips"],
            },
            {
                id: 14,
                userFullName: "Magnus Pettersen",
                userName: "MagnusP",
                email: "magnus.p@gmail.com",
                password: "hike707",
                userPicture: "img/placeholder.jpg",
                userPhysical: 4,
                location: "Fredrikstad",
                friendsListId: [12, 13, 15],
                pendingRequests: [],
                kilometresWalked: 178,
                tripsTaken: 29,
                achievementView: ["10km", "20km", "50km", "100km", "10trips", "25trips"],
            },
            {
                id: 15,
                userFullName: "Ida Solberg",
                userName: "IdaS",
                email: "ida.s@gmail.com",
                password: "path808",
                userPicture: "img/placeholder.jpg",
                userPhysical: 2,
                location: "Ski",
                friendsListId: [14, 16, 17],
                pendingRequests: [],
                kilometresWalked: 89,
                tripsTaken: 14,
                achievementView: ["10km", "20km", "50km", "10trips"],
            },
            {
                id: 16,
                userFullName: "Per Christiansen",
                userName: "PerC",
                email: "per.c@gmail.com",
                password: "trail909",
                userPicture: "img/placeholder.jpg",
                userPhysical: 5,
                location: "Halden",
                friendsListId: [15, 17],
                pendingRequests: [14],
                kilometresWalked: 267,
                tripsTaken: 41,
                achievementView: ["10km", "20km", "50km", "100km", "200km", "10trips", "25trips", "40trips"],
            },
            {
                id: 17,
                userFullName: "Kari Andersen",
                userName: "KariA",
                email: "kari.a@gmail.com",
                password: "mountain010",
                userPicture: "img/placeholder.jpg",
                userPhysical: 3,
                location: "Lillehammer",
                friendsListId: [15, 16],
                pendingRequests: [],
                kilometresWalked: 145,
                tripsTaken: 23,
                achievementView: ["10km", "20km", "50km", "100km", "10trips", "20trips"],
            },
    
        ],
        tripData: [
            {
                id: 1,
                tripName: "Hardangervidda Rundtur",
                tripPicture: "img/trip/1.png",
                tripInfo: "Vakker fjellplatå-kryssing med storslått utsikt",
                tripKM: 42,
                tripHeightChart: 1200,
                tripPhysical: 4,
                tripRating: 5
            },
            {
                id: 2,
                tripName: "Kyst Vandring",
                tripPicture: "img/trip/2.png",
                tripInfo: "Scenisk kystrute med fjordutsikt",
                tripKM: 15,
                tripHeightChart: 300,
                tripPhysical: 2,
                tripRating: 4
            },
            {
                id: 3,
                tripName: "Skogsløyfe",
                tripPicture: "img/trip/3.png",
                tripInfo: "Rundtur i tett granskog",
                tripKM: 8,
                tripHeightChart: 150,
                tripPhysical: 1,
                tripRating: 3
            },
            {
                id: 4,
                tripName: "Fjelltopp Utfordringen",
                tripPicture: "img/trip/4.png",
                tripInfo: "Bratt klatring til fjelltoppen",
                tripKM: 12,
                tripHeightChart: 1800,
                tripPhysical: 5,
                tripRating: 5
            },
            {
                id: 5,
                tripName: "Vannet Rundt",
                tripPicture: "img/trip/5.png",
                tripInfo: "Lett tur rundt fjellvann",
                tripKM: 6,
                tripHeightChart: 50,
                tripPhysical: 1,
                tripRating: 4
            },
            {
                id: 6,
                tripName: "Dalføre Traversering",
                tripPicture: "img/trip/6.png",
                tripInfo: "Lang kryssing gjennom dalen",
                tripKM: 28,
                tripHeightChart: 600,
                tripPhysical: 3,
                tripRating: 4
            },
            {
                id: 7,
                tripName: "Eggeryggen",
                tripPicture: "img/trip/7.png",
                tripInfo: "Eksponert fjellrygg-traversering",
                tripKM: 16,
                tripHeightChart: 900,
                tripPhysical: 4,
                tripRating: 5
            },
        ],
        
        achievements: {
            distance: [
                {
                    badgeName: "10km",
                    requirement: 10,
                },
                {
                    badgeName: "20km",
                    requirement: 20,
                },
                {
                    badgeName: "50km",
                    requirement: 50,
                },
                {
                    badgeName: "100km",
                    requirement: 100,
                },
                {
                    badgeName: "Marathon",
                    requirement: 42,
                }
            ],
            number: [
                {
                    badgeName: "5trips",
                    requirement: 5,
                },
                {
                    badgeName: "15trips",
                    requirement: 15,
                },
                {
                    badgeName: "30trips",
                    requirement: 30,
                },
                {
                    badgeName: "50trips",
                    requirement: 50,
                },
                {
                    badgeName: "100trips",
                    requirement: 100,
                }
            ],
        },
    },
}

//Test purposes, setter default user til Jørgine
model.app.loggedInUser = model.data.userProfile[0];